# Generated by Django 4.1.3 on 2023-01-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.FloatField()),
                ("date", models.DateField()),
                ("one_time", models.BooleanField(default=False)),
            ],
        ),
    ]
