# Generated by Django 4.1.3 on 2023-02-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_heroblock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="heroblock",
            old_name="btn_text",
            new_name="buttonText",
        ),
    ]
