# Generated by Django 4.1.3 on 2023-02-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_feature_supportedsite_pricingplan_extradetails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricingplan",
            old_name="feature",
            new_name="features",
        ),
    ]
