# Generated by Django 4.1.3 on 2023-02-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_extradetails_plan_pricingplan_extradetails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="pricingplan",
            name="extradetails",
        ),
        migrations.RemoveField(
            model_name="pricingplan",
            name="features",
        ),
        migrations.AddField(
            model_name="feature",
            name="pricing_plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="api.pricingplan",
            ),
        ),
        migrations.DeleteModel(
            name="ExtraDetails",
        ),
        migrations.DeleteModel(
            name="SupportedSite",
        ),
    ]
