# Generated by Django 4.1.3 on 2023-02-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_name_feature_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature",
            old_name="title",
            new_name="detail",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="pricing_plan",
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="features",
            field=models.ManyToManyField(related_name="features", to="api.feature"),
        ),
    ]
