# Generated by Django 4.1.3 on 2023-02-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rename_detail_supportedsites_site_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingplan",
            name="supportedsites",
            field=models.ManyToManyField(
                related_name="supportedsites", to="api.supportedsites"
            ),
        ),
    ]
