export const pricingData = [
  {
    plan: "Personal",
    title: "Personal Package",
    amount: "19",
    unit: "/month",
    features: [
      "Template Designed Website",
      "Styling and Design Control",
      "Managed VPS Hosting",
      "Content Management Tools",
      "Secure Authentication",
      "Admin Dashboard",
      "Google AdSense / Analytics",
    ],
  },
  {
    plan: "professional",
    title: "Professional",
    amount: "199",
    unit: "/month",
    features: [
      "Custom Designed Website",
      "Built to Specifications",
      "Consistent Updates on Request",
      "Styling and Design Control",
      "Content Management Tools",
      "Secure Authentication",
      "Admin Dashboard",
    ],
  },
  {
    plan: "business",
    title: "Business",
    amount: "499",
    unit: "/month",
    features: [
      "Custom Designed Website",
      "Built to Specifications",
      "Consistent Updates on Request",
      "Styling and Design Control",
      "Content Management Tools",
      "Secure Authentication",
      "Admin Dashboard",
    ],
  },
];
